# # Form implementation generated from reading ui file '工具页面.ui'
# #
# # Created by: PyQt6 UI code generator 6.4.2
# #
# # WARNING: Any manual changes made to this file will be lost when pyuic6 is
# # run again.  Do not edit this file unless you know what you are doing.
#
#
# from PyQt6 import QtCore, QtGui, QtWidgets
#
#
# class Ui_Form(object):
#
#         self.widget = QtWidgets.QWidget(parent=Form)
#
#         self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.widget)
#
#         self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
#
#         self.widget_2 = QtWidgets.QWidget(parent=self.widget)
#         self.verticalLayout = QtWidgets.QVBoxLayout(self.widget_2)
#
#         self.horizontalLayout = QtWidgets.QHBoxLayout()
#         self.pushButton = QtWidgets.QPushButton(parent=self.widget_2)
#         self.horizontalLayout.addWidget(self.pushButton)
#         self.pushButton_5 = QtWidgets.QPushButton(parent=self.widget_2)
#         self.horizontalLayout.addWidget(self.pushButton_5)
#         self.verticalLayout.addLayout(self.horizontalLayout)
#         self.pushButton.setText("下载app")
#         self.pushButton_5.setText("停止")
#
#
#
#         self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
#         self.pushButton_2 = QtWidgets.QPushButton(parent=self.widget_2)
#         self.horizontalLayout_2.addWidget(self.pushButton_2)
#         self.pushButton_6 = QtWidgets.QPushButton(parent=self.widget_2)
#         self.horizontalLayout_2.addWidget(self.pushButton_6)
#         self.verticalLayout.addLayout(self.horizontalLayout_2)
#         self.pushButton_2.setText("删除app")
#         self.pushButton_6.setText("停止")
#
#         self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
#         self.pushButton_3 = QtWidgets.QPushButton(parent=self.widget_2)
#         self.horizontalLayout_3.addWidget(self.pushButton_3)
#         self.pushButton_7 = QtWidgets.QPushButton(parent=self.widget_2)
#         self.horizontalLayout_3.addWidget(self.pushButton_7)
#         self.verticalLayout.addLayout(self.horizontalLayout_3)
#         self.pushButton_3.setText("更新app")
#         self.pushButton_7.setText("停止")
#
#
#         self.horizontalLayout_4.addWidget(self.widget_2)
#         self.textBrowser = QtWidgets.QTextBrowser(parent=self.widget)
#         self.horizontalLayout_4.addWidget(self.textBrowser)
#         self.horizontalLayout_5.addLayout(self.horizontalLayout_4)
#         self.1111.addWidget(self.widget)
#
#
